Version 0.8.10

diff --git a/plum-samples/Jenkins/dynamic-deployment.jenkinsfile b/plum-samples/Jenkins/dynamic-deployment.jenkinsfile
--- a/plum-samples/Jenkins/dynamic-deployment.jenkinsfile
+++ b/plum-samples/Jenkins/dynamic-deployment.jenkinsfile
@@ -122,33 +122,33 @@ pipeline {
         stage('Deploy: Execute The Deployment With Ansible for z/OS') {
             steps {
                 script {
-                        // Deploy
-                        rc = sh (returnStatus: true, script: '''#!/bin/sh
-                            cd ${WORKSPACE}/cics-genapp/plum-samples/external-repos/environment-conf/ansible
-                            echo $PWD
-                            rm -rf evidences
-                            CMD="ansible-playbook deploy.yml -i inventories\
-                                    -e plum_deployment_plan_file=${WORKSPACE}/BUILD-${BUILD_NUMBER}/deployment_plan.yml\
-                                    -e plum_package_file=${WORKSPACE}/BUILD-${BUILD_NUMBER}/package.tar\
-                                    ${ANSIBLE_PLAYBOOK_OPTS} ${ANSIBLE_VERBOSE_OPTS}"
-                            echo $CMD
-                            $CMD
-                            rc=$?
-                            exit $rc
+                    // Deploy
+                    rc = sh (returnStatus: true, script: '''#!/bin/sh
+                        cd ${WORKSPACE}/cics-genapp/plum-samples/external-repos/environment-conf/ansible
+                        echo $PWD
+                        rm -rf evidences
+                        CMD="ansible-playbook deploy.yml -i inventories\
+                                -e plum_deployment_plan_file=${WORKSPACE}/BUILD-${BUILD_NUMBER}/deployment_plan.yml\
+                                -e plum_package_file=${WORKSPACE}/BUILD-${BUILD_NUMBER}/package.tar\
+                                ${ANSIBLE_PLAYBOOK_OPTS} ${ANSIBLE_VERBOSE_OPTS}"
+                        echo $CMD
+                        $CMD
+                        rc=$?
+                        exit $rc
+                    ''')
+                    if ( rc != 0 )
+                        error("Deploy Ansible Deployment Failed!!!")
+                    // Git Push
+                    rc = sh (returnStatus: true, script: '''#!/bin/sh
+                         cd ${WORKSPACE}/cics-genapp
+                         cp ${WORKSPACE}/cics-genapp/plum-samples/external-repos/environment-conf/ansible/evidences/* plum-samples/external-repos/evidences
+                         git add plum-samples/external-repos/deployment-state/deployment_state.yml
+                         git add plum-samples/external-repos/evidences/*
+                         git commit -am "Commit new deployment state to ${GIT_BRANCH} branch for the current environment"
+                         git push origin HEAD:${GIT_BRANCH}
                         ''')
-                        if ( rc != 0 )
-                            error("Deploy Ansible Deployment Failed!!!")
-                        // Git Push
-                        rc = sh (returnStatus: true, script: '''#!/bin/sh
-                             cd ${WORKSPACE}/cics-genapp
-                             mv ${WORKSPACE}/cics-genapp/plum-samples/external-repos/environment-conf/ansible/evidences/* plum-samples/external-repos/evidences
-                             git add plum-samples/external-repos/deployment-state/deployment_state.yml
-                             git add plum-samples/external-repos/evidences/*
-                             git commit -am "Commit new deployment state to ${GIT_BRANCH} branch for the current environment"
-                             git push origin HEAD:${GIT_BRANCH}
-                            ''')
-                        if ( rc != 0 )
-                            error("Git Push Failed!!!")
+                    if ( rc != 0 )
+                        error("Git Push Failed!!!")
                 }
             }
             post {
