Evidences Enhancements

diff --git a/plum-samples/Jenkins/dynamic-deployment.jenkinsfile b/plum-samples/Jenkins/dynamic-deployment.jenkinsfile
--- a/plum-samples/Jenkins/dynamic-deployment.jenkinsfile
+++ b/plum-samples/Jenkins/dynamic-deployment.jenkinsfile
@@ -169,6 +169,52 @@ pipeline {
                 }
             }
         }
-        
+
+        stage('Deploy: Deployment Report') {
+            steps {
+                script {
+                    if ( hasBuildFiles ) {
+                        rc = sh (returnStatus: true, script: '''#!/bin/sh
+                            mkdir -p ${WORKSPACE}/BUILD-${BUILD_NUMBER}/deploy/index
+                            # Index Evidences
+                            CMD="plum-evidence\
+                                --indexFolder ${WORKSPACE}/BUILD-${BUILD_NUMBER}/deploy/index\
+                                --dataFolder ${WORKSPACE}/cics-genapp/plum-samples/external-repos/environment-conf/ansible/evidences\
+                                i"
+                            echo $CMD
+                            $CMD 
+                            if [ $? -ne 0 ]
+                            then
+                              exit $?
+                            fi
+                            # Query Index
+                            CMD="plum-evidence\
+                              --indexFolder ${WORKSPACE}/BUILD-${BUILD_NUMBER}/deploy/index\
+                              --template ${WORKSPACE}/cics-genapp/plum-samples/evidences/templates/full-report.yml\
+                              --output=${WORKSPACE}/BUILD-${BUILD_NUMBER}/deploy/deployment-report.html\
+                              r\
+                              renderer=${WORKSPACE}/cics-genapp/plum-samples/evidences/renderers/full-report.html"
+                            echo $CMD
+                            $CMD 
+                            if [ $? -ne 0 ]
+                            then
+                              exit $?
+                            fi
+                      ''')
+                      if ( rc != 0 )
+                          error("Excecution Of Deployment Report Failed!!!")
+                     }
+                }
+            }
+            post {
+                always {
+                    dir("${WORKSPACE}/BUILD-${BUILD_NUMBER}") {
+                        archiveArtifacts allowEmptyArchive: true,
+                                        artifacts: '**/deployment-report.html',
+                                        onlyIfSuccessful: false
+                    }
+                }
+            }
+        }
     }
 }
