Evidences Enhancements

diff --git a/plum-samples/Jenkins/static-build-upload-download-deploy.jenkinsfile b/plum-samples/Jenkins/static-build-upload-download-deploy.jenkinsfile
--- a/plum-samples/Jenkins/static-build-upload-download-deploy.jenkinsfile
+++ b/plum-samples/Jenkins/static-build-upload-download-deploy.jenkinsfile
@@ -273,5 +273,58 @@ pipeline {
                 }
             }
         }
+        
+        stage('Deploy: Deployment Report') {
+            steps {
+                script {
+                    if ( hasBuildFiles ) {
+                        rc = sh (returnStatus: true, script: '''#!/bin/sh
+                            if [ "$PYTHON_VIRTUAL_ENV_COMMAND" != "" ]
+                            then
+                               echo "Use a virtual env $PYTHON_VIRTUAL_ENV_COMMAND"
+                               . $PYTHON_VIRTUAL_ENV_COMMAND
+                               export PYTHON_INTERPRETER="python3"
+                            else
+                               export PATH=$PATH:$HOME/.local/bin
+                            fi
+                            # Index Evidences
+                            CMD="plum-evidence\
+                                --indexFolder ${WORKSPACE}/BUILD-${BUILD_NUMBER}/deploy/index\
+                                --dataFolder ${WORKSPACE}/BUILD-${BUILD_NUMBER}/deploy/evidences\
+                                i"
+                            echo $CMD
+                            $CMD 
+                            if [ $? -ne 0 ]
+                            then
+                              exit $?
+                            fi
+                            # Query Index
+                            CMD="plum-evidence\
+                              --indexFolder ${WORKSPACE}/BUILD-${BUILD_NUMBER}/deploy/index\
+                              --template ${WORKSPACE}/cics-genapp/plum-samples/evidences/templates/full-report.yml\
+                              --output=${WORKSPACE}/BUILD-${BUILD_NUMBER}/deploy/deployment-report.html\
+                              r"
+                            echo $CMD
+                            $CMD 
+                            if [ $? -ne 0 ]
+                            then
+                              exit $?
+                            fi
+                      ''')
+                      if ( rc != 0 )
+                          error("Excecution Of Deployment Report Failed!!!")
+                     }
+                }
+            }
+            post {
+                always {
+                    dir("${WORKSPACE}/BUILD-${BUILD_NUMBER}") {
+                        archiveArtifacts allowEmptyArchive: true,
+                                        artifacts: '**/deployment-report.html',
+                                        onlyIfSuccessful: false
+                    }
+                }
+            }
+        }
     }
 }
