zCode Scan Proto

diff --git a/wazideploy-samples/Jenkins/static-build-upload-download-deploy-python.jenkinsfile b/wazideploy-samples/Jenkins/static-build-upload-download-deploy-python.jenkinsfile
--- a/wazideploy-samples/Jenkins/static-build-upload-download-deploy-python.jenkinsfile
+++ b/wazideploy-samples/Jenkins/static-build-upload-download-deploy-python.jenkinsfile
@@ -162,6 +162,29 @@ pipeline {
             }
         }
 
+        stage('Upload Static Analysis to SonarQ') {
+            when {
+                expression { rollingBack == false } 
+            }
+            steps {
+                script{
+                    if ( hasBuildFiles ) {
+                        rc = sh (returnStatus: true, script: '''#!/bin/sh
+                            cd /tmp/zcodescan
+                            ./sonar.sh
+                            if [ $? -ne 12 ]
+                            then
+                              exit $?
+                            fi
+                            exit 0
+                        ''')
+                        if ( rc != 0 )
+                            error("Uploading Package failed!!!")
+                    }
+                }
+            }
+        }
+
         stage('Package & Artifactory Upload') {
             when {
                 expression { rollingBack == false } 
